[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
diesel = { version = "2",features = ["sqlite", "returning_clauses_for_sqlite_3_35"]}
diesel_migrations = "2"
libsqlite3-sys = { version = "0.35",features = ["bundled"]}

[dev-dependencies]
tempfile = "3.27.0"
